language: "ruby"
sudo: false
cache: "bundler"
matrix:
  include:
    - rvm: "3.0"
  fast_finish: true
script: "bundle exec rake"
before_install:
  - "gem update --system"
  - "gem update bundler"
services:
  - "redis-server"
if: "type != push OR (tag IS blank AND branch = main)"
notifications:
  email: false
